### ISSUE TITLE
local document definitions

### ISSUE THREAD

**Issue by haobole** [x12ruby/x12#8]
I am interested in replacing my own reworking of  http://www.appdesign.com/x12parser/ with your gem, but I have one question that I cannot figure out. I never know what kind of document my customer sent me until after I parse it, so I cannot use this syntax since it assumes that I know in advance the file type:

`parser = X12::Parser.new('misc/997.xml').parse('997', document_as_string)`

What I ended up doing in my own code is creating a meta-definition file container.xml that contain all the different possible files types that could be sent. So I use something like this:

`full = X12::Parser.new('/lib/edi_document_definitions/container.xml').parse('container', raw)`

However, when I try to integrate with your gem, and I use this syntax, then it looks for the rest of the sub-definitions in my lib/edi_document_definitions directory instead of the misc directory of your gem. But I want to use your misc directory for the sub-definitions. I don't want to duplicate in my local directory the contents of your misc directory.

Am I trying to use your gem wrongly? Am I the only person who needs to create local definitions to supplement your definitions?

**Comment by swalberg** [comment]
Hi, thanks for this report. What you are describing is a perfectly reasonable expectation but there's some hard coding in the gem that doesn't allow it. See:

https://github.com/x12ruby/x12/blob/master/lib/x12/parser.rb lines 67 and 138. The directory of the first file loaded is saved and used to load documents later.

What I did in the project that used this is duplicate the `misc` directory and put in my own container document. What you are suggesting is a better option IMHO.

I believe the fix could be fairly simple as the file processing is pretty much limited to `parser.rb`. I can't think of a generic way to specify search paths other than a class variable (trying to avoid needing a config file as this gem currently doesn't need one).

Any thoughts?

**Comment by prelude12** [comment]
Hi Philip,

This a rather common problem, but not the only one - messages can be of different types inside one interchange. The X12::Parser expects a single transaction. So, you can do one of the following:
1. Include the ISA and GS envelopes in transaction definition for each type of transactions you can reasonably expect. Something like this:

<Loop name='all'>
  <Loop name="997">
      <Segment name="ST"  max="1">
        <Field name="TransactionSetIdentifierCode" const="997"/>
        ....
  <Loop name="835">
      <Segment name="ST"  max="1">
        <Field name="TransactionSetIdentifierCode" const="835"/>
        ....

... and so on. Then have a big switch statement and check for the right TransactionSetIdentifierCode.
1. Pre-parse the interchange and feed the X12::Parser only ST...SE fragments.
2. Write an addition to X12::Parser that will do all this dirty work automatically. We did not do it because our clients send us only one transaction type per interchange.

Hope this helps.

Yours,
Ivan

**Comment by prelude12** [comment]
Hi Sean,

I’ve just noticed that rubyforge.org is gone. Feel free to apply your fix to the github repository. As for search path, I can suggest doing what Ant does – search for the file from the script’s own directory upward.

Yours,
Ivan
